version: "3.0"

services:
  quarkus-db:
    image: mysql:latest
    container_name: quarkus-db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=produtos-db

    ports:
      - 45060:3306


    networks:
      - quarkus-network

  quarkus-api:
    build: 
      context: .
      dockerfile: src/main/docker/Dockerfile.native

    restart: always

    depends_on:
      - quarkus-db

    networks:
      - quarkus-network

    ports:
      - 8080:8080


networks:
  quarkus-network:
    driver: bridge